# Generated by Django 4.2.5 on 2023-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cigarettes_per_day', models.PositiveIntegerField()),
                ('exercise_per_week', models.DurationField()),
                ('reaction_time_ms', models.PositiveIntegerField()),
                ('alcohol_per_week', models.PositiveIntegerField()),
                ('sitting_duration_per_day', models.DurationField()),
            ],
        ),
    ]
